stages:
  - test
  
code_quality:
  #image: docker:stable
  #image: mcr.microsoft.com/windows/servercore:1809_amd64
   - echo "${DOCKER_AUTH_CONFIG}" > ~/.docker/config.json
   - docker login nexagen-dev.usgovvirginia.cloudapp.usgovcloudapi.net:5050
  image: fee6961cfa3e
  variables:
    DOCKER_DRIVER: overlay2
    SP_VERSION: 0.85.6
  allow_failure: true
  #services:
  #  - docker:stable-dind
  script:
    - docker run
        --env SOURCE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/ci-cd/codequality:$SP_VERSION" /code
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
